name: servicio_tecnico
description: "Aplicación para servicio técnico de celulares."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: 0.19.0
  provider: ^6.1.2
  pdf: ^3.11.1
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  screenshot: ^3.0.0
  extended_masked_text: ^3.0.1
  flutter_riverpod: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  generate: true # Add this line

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher-web.png"
